### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by TheSpiike** [alphak3y/SuperMine#1]
clicking icon did not load the binary but opening terminal gave this error. verified that the config was setup correctly.

Traceback (most recent call last):
  File "validator.py", line 11, in <module>
    from blspy import G1Element, PrivateKey
ModuleNotFoundError: No module named 'blspy'
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f0dc1018130>
terminate called after throwing an instance of 'std::invalid_argument'
  what():  stoi
Aborted (core dumped)

Setup is as follows
Ubuntu 20.10
Chia 1.2.0
Supermine 0.1.5
3700x 32gb ram running veruscoin mining software
1 external drive 3TB with 27 plots 
running harvester mode which sync with my full node
other rig is farmer and full node 908 plots

**Comment by alphak3y** [comment]
Same core dump as the other issue.

In addition there is a Python dependency missing.

**Comment by TheSpiike** [comment]
I ran these commands

`sudo apt-get install libcurl4 libcurl4-openssl-dev -y`
`sudo apt-get install python3 -y`
`sudo apt-get install python3-pip -y`
`pip3 install chia-blockchain`

then this happens

> Unclosed client session
>
>client_session: <aiohttp.client.ClientSession object at 0x7f1f0a1271c0>
>terminate called after throwing an instance of 'std::invalid_argument'
>  what():  stoi
>Aborted (core dumped)

**Comment by TheSpiike** [comment]
0.1.5a

clicking on Supermine does nothing.
errors.txt file says

>FAILURE CODE: 9

and the terminal window shows

>sh: 1: chia: not found

verfied that the config was correct

`Chia_Config_Path="/home/spiike/.chia/mainnet/"`

and verified that the harvester is currently running

> harvester chia.harvester.harvester: INFO     0 plots were eligible for farming

**Comment by alphak3y** [comment]
** Patched in 0.1.5a **
