### ISSUE TITLE
Software crash

### ISSUE THREAD

**Issue by R00573R** [alphak3y/SuperMine#2]
Directory: /sys/devices/pci0000:00/0000:00:08.1/0000:0c:00.3/usb4/4-3/4-3:1.0/host6/target6:0:0/6:0:0:0/block/sdb does not exist.
Directory: /sys/devices/pci0000:00/0000:00:01.2/0000:02:00.1/ata4/host3/target3:0:0/3:0:0:0/block/sda does not exist.
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f81223963d0>
terminate called after throwing an instance of 'std::invalid_argument'
  what():  stoi
Aborted (core dumped)

**Comment by alphak3y** [comment]
Apparently this is not an error...just a warning

https://stackoverflow.com/questions/54807599/aiohttp-unclosed-client-session-client-session

Somehow this is preventing the client from starting looks like.

To Python it is a warning but then somehow the C++ program does a coredump.

**Comment by amuDev** [comment]
> Apparently this is not an error...just a warning
> 
> https://stackoverflow.com/questions/54807599/aiohttp-unclosed-client-session-client-session
> 
> Somehow this is preventing the client from starting looks like.
> 
> To Python it is a warning but then somehow the C++ program does a coredump.

Core dumped due to no error handle, we are trying to return a string as an int value but the string is never being set (related to bad client session) so we try to stoi a null string.

New error handling has been added. Investigating bad client session.

**Comment by alphak3y** [comment]
**Patched in 0.1.5a**
